/** @type {import('tailwindcss').Config} */
const v = (name) => `rgb(var(--${name}) / <alpha-value>)`;

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-void': v('bg-void'),
        'bg-panel': v('bg-panel'),
        'bg-panel-raised': v('bg-elevated'),
        'bg-elevated': v('bg-elevated'),
        'bg-hover': v('bg-hover'),
        'border-subtle': v('border-subtle'),
        'border-strong': v('border-strong'),
        'border-hairline': v('border-subtle'),
        'text-primary': v('text-primary'),
        'text-secondary': v('text-secondary'),
        'text-muted': v('text-muted'),
        'text-mono': v('text-muted'),
        accent: v('accent'),
        'accent-primary': v('accent'),
        'accent-fg': v('accent-fg'),
        'accent-danger': v('danger'),
        'accent-warn': v('warning'),
        'accent-electric': v('accent'),
        success: v('success'),
        danger: v('danger'),
        warning: v('warning'),
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'ui-monospace', 'monospace'],
      },
      boxShadow: {
        panel: 'var(--shadow-panel)',
        glow: 'var(--shadow-glow)',
      },
      typography: () => ({
        algo: {
          css: {
            '--tw-prose-body': 'rgb(var(--text-secondary))',
            '--tw-prose-headings': 'rgb(var(--text-primary))',
            '--tw-prose-lead': 'rgb(var(--text-secondary))',
            '--tw-prose-links': 'rgb(var(--accent))',
            '--tw-prose-bold': 'rgb(var(--text-primary))',
            '--tw-prose-counters': 'rgb(var(--text-muted))',
            '--tw-prose-bullets': 'rgb(var(--text-muted))',
            '--tw-prose-hr': 'rgb(var(--border-subtle))',
            '--tw-prose-quotes': 'rgb(var(--text-primary))',
            '--tw-prose-quote-borders': 'rgb(var(--accent))',
            '--tw-prose-code': 'rgb(var(--text-primary))',
            '--tw-prose-pre-code': 'rgb(var(--text-primary))',
            '--tw-prose-pre-bg': 'rgb(var(--bg-elevated))',
            '--tw-prose-th-borders': 'rgb(var(--border-strong))',
            '--tw-prose-td-borders': 'rgb(var(--border-subtle))',
            fontSize: '0.96rem',
            lineHeight: '1.8',
            maxWidth: '72ch',
            'h1,h2,h3': { letterSpacing: '-0.015em', fontWeight: '650' },
            h2: { marginTop: '2em', paddingBottom: '0.3em', borderBottom: '1px solid rgb(var(--border-subtle))' },
            p: { marginTop: '1em', marginBottom: '1em' },
            'code::before': { content: '""' },
            'code::after': { content: '""' },
            ':not(pre) > code': {
              background: 'rgb(var(--bg-elevated))',
              border: '1px solid rgb(var(--border-subtle))',
              padding: '0.15em 0.4em',
              borderRadius: '0.375rem',
              fontSize: '0.86em',
              fontWeight: '500',
            },
            pre: {
              border: '1px solid rgb(var(--border-subtle))',
              borderRadius: '0.75rem',
              lineHeight: '1.6',
            },
            a: { textDecoration: 'none', fontWeight: '500', '&:hover': { textDecoration: 'underline' } },
            'ul > li, ol > li': { marginTop: '0.35em', marginBottom: '0.35em' },
          },
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
