export class ResponseData {
    responseCode: number
    responseMessage: string
    data: any

    private constructor(responseCode: number, responseMessage: string, data: any = undefined) {
        this.responseCode = responseCode;
        this.responseMessage = responseMessage;
        this.data = data;
    }

    public static build(code: number, message: string, data: any = undefined) {
        return new ResponseData(code, message, data)
    }
}

export const RESPONSE_MESSAGES = {
    SUCCESS : 'success',
    WALLET_SERVER_ERROR : 'something went wrong in wallet. please contact support',
    SOMETHING_WENT_WRONG : 'Something went wrong. Please contact support.',
    TEST_CONFIG_FAILED : 'Please use the valid phone number or Try with another base phone number',
    AUTHORIZATION_FAILED: 'api token not valid',
    THEFT_OCCUR : "Security Alert: Invalid token. Account secured and logged out.",
    DUPLICATE_DEVICE: 'duplicate device, a device can only be used with two different mobile number',
    DUPLICATE_COLUMN: 'is already used by another user',
    LOGIN_OTP_LIMIT_REACHED : 'OTP limit reached',
    OTP_LIMIT_REACHED: 'OTP Limit exceeded. Please try after 15 minutes or use other documents for KYC',
    VOICE_OTP_LIMIT_REACHED: `You have exceeded {0} attempts. Kindly visit after sometime.`,
    TRUE_CALLER_FAILED: 'mobile verification failed',
    INTERNAL_KYC_STATUS_FAILURE: 'internal kyc status api failed',
    FACE_BOOK : 'faceBook verification failed',
    INVALID_MOBILE: 'invalid mobile number',
    INVALID_OTP: 'invalid otp',
    TRANSACTION_ROLLBACK: 'cannot save data at the moment',
    FREE_APP_FAILURE: 'User already exist in paid app',
    INVALID_DEVICE_TOKEN: 'invalid device token',
    MISSING_LANGUAGE_CODE : 'language code not provided',
    INVALID_INPUT: 'invalid input',
    INVALID_PAN_INPUT: 'please enter both PAN and Date of Birth',
    INVALID_TOKEN: 'invalid token',
    INVALID_SCOPE: 'invalid scope',
    UNKNOWN_FIELD: 'unknown field',
    INVALID_POST_AUTH_VERIFICATION_STATE : 'invalid post auth verification state',
    INVALID_REFER_CODE: 'invalid referCode',
    DUPLICATE_REPORT_USER: 'your have already reported this user',
    EMPTY_REGISTRATION_ID: 'registrationId header is not present',
    EMPTY_REGISTRATION_ID_AND_MOBILE: 'both registrationId and mobile header are not present',
    EMPTY_COUNTRY_ID : 'CountryId not present',
    ALREADY_EXIST: 'Already Exist',
    USER_NOT_FOUND: 'User does not exist',
    USER_NOT_FOUND_IN_AB_SERVICE: 'User not found in AB Service',
    CROSS_INFRA_FETCH_FAILED: 'Failed to fetch user profile from cross-infra service',
    VIDEO_NOT_FOUND: 'Video does not exist',
    CHANNEL_NOT_FOUND: 'Channel does not exist',
    THIRD_PARTY_NOT_FOUND: 'Third party does not exist',
    DEAL_NOT_FOUND: 'Deal does not exist',
    WRONG_DATA_INPUT: 'Entered wrong data',
    UNLOCK_COMMISSION_DATA_NOT_FOUND: "Unlock commission data not found",
    USER_NOT_EXPERT: 'User is not an expert.',
    USER_ALREADY_VERIFIED: 'User is already verified.',
    ENTRY_NOT_PRESENT : 'Entry not present',
    KYC_DATA_EXTRACTION_PENDING : 'Kyc data extraction pending',
    SIGNZY_AUTHORIZATION_FAILURE : 'Auth failed for the request id',
    INVALID_DRIVING_LICENCE: 'Invalid Driving Licence',
    INVALID_VOTER_ID : 'Invalid Voter Id',
    INVALID_PAN: 'Invalid PAN',
    KYC_DATA_EXTRACTION_FAILED: 'Kyc data extraction failed',
    KYC_LIMIT_EXCEEDED: 'Kyc attempt limit reached. Try after 30 minutes.',
    TIMEOUT : 'Request timed out',
    KYC_PAN_ALREADY_EXIST : 'PAN Already exist',
    INVALID_COUPON: 'Invalid Coupon Code',
    FAILED_ADDING_DATA_TO_DB: 'Failed adding data to the database',
    SS_NEW_WALLET_ERROR: 'Superstar new wallet error',
    USER_NOT_SUPERSTAR: 'User is not a superstar',
    PENDING: 'Pending',
    FAILED: 'Failure',
    TRANSACTION_ID_REQUIRED: 'Valid Transaction id is required',
    TRANSACTION_ID_DOES_NOT_EXIST: 'Transaction id does not exist',
    PENDING_MESSAGE: 'You should receive your withdrawal amount in 3 business days else we will refund your withdrawal amount to your Winzo wallet',
    REFUND_STATUS: 'We already refunded your withdrawal amount in your Winzo wallet.',
    SUCCESS_TRANSACTION: 'Success',
    SUCCESS_STATUS_MESSAGE: 'Congratulations!, your Withdrawal amount Rs.10.00 is credited to your Paytm Wallet. Your withdrawal charges are Rs.undefined',
    PENDING_RESPONSE: 'Your Withdrawal request has been accepted. Post successful verification of your request, you will receive your withdrawal amount in next 8 hours',
    STATUS_FAILED: 'Failed',
    NOT_FOUND :"Requested data doesn't exist",
    INVALID_USER_CONFIG: 'Invalid User Config',
    INVALID_RAKE_PROFILING_CONFIG_INPUTS: 'Invalid profileId or multiplier',
    INCORRECT_FETCH_USER_PROFILE_INPUT: 'Give either mobile or registrationId at a time',
    USER_BLOCKED : 'User Blocked',
    NOT_ALLOWED: 'Can not change name',
    INVALID_CONFIG : 'invalid config',
    COUNTRY_NOT_FOUND : 'Can not find Country for the given user.',
    STATE_LIST_NOT_FOUND : 'Can not find states for the given country.',
    ACCOUNT_DELETED : 'Account Deleted',
    ACCOUNT_DEACTIVATED :  'Account Deactivated',
    ACCOUNT_DELETION_IN_PROGRESS: 'Account deletion in progress',
    UNSUPPORTED_CURRENCY: 'Unsupported Currency',
    TOGGLE_NOT_ALLOWED_PERIOD: function<T extends number|string> (t: T) {
        return typeof t === 'string' ? `Toggle is disabled for ${t}` : `Toggle is disabled for ${t} minutes`;
    },
    TOGGLE_SWITCHED_OFF: 'Toggle function is currently disabled. Please contact support.',
    TOGGLE_NOT_ALLOWED: 'Toggle not allowed for the currency',
    ACCOUNT_ACTIVATION_NOT_ALLOWED:'Account activation not allowed.',
    INVALID_NAME: 'You cannot use special characters or numbers in your name.',
    INVALID_EMAIL: 'Invalid Email address.',
    INVALID_CITY: 'Invalid City name.',
    INVALID_ABOUT_ME: 'You cannot use special characters or numbers.',
    INVALID_ROLE_ID : 'You have entered invalid role id',
    INVALID_ACTION : 'Invalid Action',
    INVALID_OR_EMPTY_FILE : 'Invalid or empty File. It should be CSV.',
    INVALID_OR_EMPTY_BODY : 'Invalid or empty body. It should have array of usersList.',
    RATE_LIMIT_ERROR: 'Too many attempts',
    POST_AUTH_VERIFY_FAILURE: 'post auth verification failed',
    POST_AUTH_VERIFY_LOGGED:'post auth verification for logging',
    INVALID_DOC_NUMBER : 'invalid doc number',
    PREMIUM_USER_ACTIVE_VERSION_NOT_FOUND: 'No active version found for premium user.',
    DB_ERROR : 'DB_ERROR',
    CC_RESOLVER_NOT_FOUND : 'cc resolver not found',
    LOYALTY_BENEFITS_CONFIG_NOT_FOUND : 'loyalty benefits config not found',
    CLUB_TIER_CONFIG_NOT_FOUND : 'club tier config not found',
    INVALID_DOC_TYPE : 'invalid doc type',
    INVALID_SELF_INCOME_STATE : 'invalid self income verification state',
    INVALID_REWARD_TYPE : "Invalid Reward Type",
    OFFER_SERVICE_ERROR : 'offer service exception',
    INVALID_FILE_FORMAT : `Invalid file format, Allowed file types are ["png", "jpeg", "jpg"]`,
    RG_INVALID_FILE_FORMAT : `Invalid file format, Allowed file types are ["pdf"]`,
    LIMIT_FILE_SIZE : `File is too large, Allowed size is 5 MB`,
    INVALID_APP : 'This app is no longer supported. Please update from the WinZO website. ',
    BAD_REQUEST: 'Bad request to server',
    UNAUTHORIZED: 'Unauthorized',
    INVALID_CSV_FILE : 'Invalid CSV file',
    KYC_DELINK_LIMIT_EXCEEDED : 'More than 10 regIds not supported',
    INVALID_RAKE_THRESHOLDS : 'Invalid rake thresholds',
    CONFIG_ALREADY_UPDATED: 'Config is already updated',
    UNPROCESSED_JOB_ALREADY_EXISTS: 'An unprocessed job already exists',
    INVALID_JOB_DELAY: 'Invalid go-live date. It should be from current to next 15d',
    INVALID_JSON: 'Invalid or empty JSON',
    INVALID_COUNTRY: 'Invalid country in request',
    ALREADY_IN_PROGRESS: 'Already in progress',
    INELIGIBLE_FOR_PROGRESSION: 'User is not eligible for progression',
    ACCOUNT_ALREADY_EXISTS: 'Account already exists',
    ACCOUNT_ALREADY_EXISTS_WINZO_TV: 'Account already exists winzo tv',
    ENTER_EITHER_KYC_HASH_OR_REG_ID: 'Either kycHash or regId should be entered',
    GOOGLE_SSO_AUTHORIZATION_FAILED : 'Google SSO authorization failed',
    APPLE_SSO_AUTHORIZATION_FAILED : 'Apple SSO authorization failed',
    FACEBOOK_SSO_AUTHORIZATION_FAILED : 'Facebook SSO authorization failed',
    REMOVING_GUEST_ACCOUNT_WARNING : 'Removing Guest account warning',
    GMAIL_LOGIN_MODE_TOGGLE_SUCCESS : 'Gmail login mode {isActive} for country {countryId} and app version {appVersion}',
    SSO_EMAIL_COLLISION_ERROR : 'SSO email collision error',
    INVALID_JWT : 'Invalid Jwt',
    DELINK_REQUEST_WITH_SINGLE_SSO : 'Delink request with single SSO',
    SAME_SSO_EMAIL_COLLISION_FAILURE : 'Same SSO email collision error',
    USER_NOT_FOUND_FOR_SESSION_MIGRATION : 'User not found for session migration',
    AUTHENTICATE_EXISTING_ACCOUNT : 'Authenticate existing account',
    CROSS_INFRA_SSO_ACCOUNT_DETECTED : 'Cross infra SSO account detected',
    CROSS_INFRA_GUEST_ACCOUNT_DETECTED : 'Cross infra guest account detected',
    CROSS_INFRA_SIGNUP_DETECTED : 'Cross infra signup detected',
    INVALID_MIGRATION_INPUT: 'Invalid migration input',
    MISSING_REQUIRED_MIGRATION_CONSENTS: 'Missing required consents for migration',
    MIGRATION_CONFIG_NOT_SET_UP: 'User migration configuration is not set up',
    CONSENT_NOT_FOUND: 'User consent not found for migration',
    PARENT_USER_NOT_FOUND: 'Parent user does not exist',
    CHILD_USER_NOT_FOUND: 'Child user does not exist',
    CHILD_ALREADY_REFERRED: 'Child user already has a referral',
    PARENT_CREATED_AFTER_CHILD: 'Parent user was created after child user',
    WALLET_TRIGGER_FAILED: 'Failed to trigger referral worker in wallet service',
}

export const RESPONSE_CODES = {
    SUCCESS: 1,
    FAILURE: 500,
    AUTHORIZATION_FAILED: 1002,
    DUPLICATE_DEVICE: 1003,
    OTP_LIMIT_REACHED: 1004,
    INVALID_OTP: 1005,
    INVALID_TOKEN: 1006,
    INVALID_REFER_CODE: 1007,
    DUPLICATE_REPORT_USER: 1008,
    ALREADY_EXIST: 1009,
    NOT_ELIGIBLE_FOR_RAKEBACK: 1010,
    USER_NOT_EXPERT : 1011,
    INVALID_INPUT: 400,
    KYC_DATA_EXTRACTION_PENDING : 1012,
    KYC_HASH_MISMATCH : 1013,
    INVALID_DRIVING_LICENCE : 1014,
    KYC_LIMIT_EXCEEDED : 1015,
    TIMEOUT : 1016,
    DRIVING_LICENCE_LIMIT_REACHED : 1017,
    KYC_PAN_ALREADY_EXIST : 1018,
    DATA_UNAVAILABLE : 1019,
    BAD_REQUEST: 404,
    UNAUTHORISED : 401,
    UPDATE_APP : 419,
    NOT_ALLOWED : 1020,
    UNPROCESSABLE_ENTITY: 422,
    KYC_INITIATION_FAILED : 1021,
    UNAUTHORIZED_APP : 480,
    BAD_REQUEST_TO_SERVER : 400,
    NOTIFICATION_CENTER_ERROR : 408,
    INVALID_PAN : 1021,
    VALIDATION_FAILED : 1022,
    RATE_LIMIT_ERROR : 210,
    REDIS_LOCK_APPLIED : 1023,
    SUCCESS_HTTP_CODE : 200,
    INVALID_REQUEST : 211,
    DATA_EXISTS_AS_SUCCESS : 310,
    POST_AUTH_VERIFY_FAILURE : 311,
    POST_AUTH_VERIFY_RATE_LIMIT:312,
    POST_AUTH_VERIFY_NON_RATE_LIMIT:313,
    NOT_AVAILABLE : 404,
    ALREADY_EXISTS : 409,
    NOT_MODIFIED : 304,
}

